### ISSUE TITLE
Cannot connect in a browser in Zowe tutorial

### ISSUE THREAD

**Issue by kazufumiw** [zowe/zlux-app-server#41]
Hi, 
This is using the tutorial, ["Getting started with the ZOWE WebUi"](https://developer.ibm.com/tutorials/zowe-step-by-step-tutorial/).

I have a trouble at the 4th step, "***Run the Server***".
I entered the following command in the directory```~/zlux/zlux-app-server/bin/```(because there is no zlux-example-server.)
```
./nodeServer.sh -h 192.86.32.67 -P 8542 -p 5000
```
then accessed the webpage and entered my ID and password, but this kind of error occurred.
```
Authetication failed for 1 types. Types: ["zss"]
```

How can I solve it?
I think the problem involves not replacing "8542" with my zss port number, but I can't find the port number...

**Comment by 1000TurquoisePogs** [comment]
Yes - the tutorial has been updated to use "zlux-app-server" now. But, note a few configuration items which may resolve this:
1. The IP for -h may have changed from `192.86.32.67`
2. In zowe 1.0.1 onward, the ZSS server only listens on localhost by default. It's recommended to configure ATTLS for ZSS to use HTTPS, especially if altering it to listen externally, but for the purpose of the tutorial you can just edit the behavior of what port ZSS listens on via `agent.http.port`, and what address it listens on via `agent.http.ipAddresses` within the zluxserver.json file, as you see here: https://github.com/zowe/zlux-app-server/blob/master/config/zluxserver.json#L26
At runtime, this file is located at
`zlux-app-server/deploy/instance/ZLUX/serverConfig/zluxserver.json`

Please reopen if this is not solved by these changes. Thank you!
